app:
  jwtExpirationInMs: 604800000
  jwtSecret: JWTSuperSecretKey
  jwtSecretIntegration: JWTSuperSecretKey
  aws:
    region: sa-east-1
    s3:
      bucket: entrepatas
      baseUrl: https://entrepatas.s3-sa-east-1.amazonaws.com
    iam:
      access_key_id: AKIA4JEATZWMMFXWQIMX
      secret_access_key: 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
  url:
    send-email: entrepatasch.com/#/active-acount?code-validation=
  urlTeki: http://localhost:8080/api
  tokenTeki: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTkyMzYzMTk0fQ.VFUMWpIuyrFLnu97lrxG3alOIocps9dg85fvN43ExrqGxcjmJdKjXwnhV8U6zdDEP9OqhZxw-IlsGtrWXrFwNQ
server:
  port: 9002
spring:
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: spiderman
    url: jdbc:mysql://localhost:3306/db_entrepatas?useSSL=false&serverTimezone=America/Lima
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
  mail:
    from: luisyum@gmail.com
    host: email-smtp.us-east-2.amazonaws.com
    username: AKIA4JEATZWMMB43BLFT
    password: BJzfyA110pOggr4R0uZY+siVkYg2l5LdN9p/L41ex/ZY
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 587
          auth: true

  sendgrid:
    api-key: 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
email:
  templates:
    templateResetPassword:
      subject: Solicitud de cambio de contraseña
    templateActiveAccount:
      subject: Activación de cuenta
    templatePostulante:
      subject: Solicitud de adopción
  from: luisyum@gmail.com
  name: EntrePatas

feign:
  httpclient:
    connection-timeout: 300000

