package app.ws.entrepatas.model;

public enum RoleName {

    //ADMINISTRADOR
    ROLE_USER,
    ROLE_PERFIL,

    //REPORT
    ROLE_REPORTE,
    ROLE_REPORTE_NO_COBERTURADO,

    //PUBLICACIONES
    ROLE_PUBLICACION_REGISTRO,
    ROLE_PUBLICACION_LISTADO,
    ROLE_PUBLICACION_HISTORIAL_CLINICO,
    ROLE_PUBLICACION_APROBACION,

    // ADOPCION
    ROLE_ADOPCION_POSTULANTE_LISTADO,
    ROLE_ADOPCION_GENERAR,
    ROLE_ADOPCION_LISTADO,
    ROLE_ADOPCION_DEVOLUCION,

    //EVENTOS
    ROLE_EVENTO_GENERA,
    ROLE_EVENTO_LISTADO,
    ROLE_EVENTO_TIPO,

    // COLABORA REFUGIO

    ROLE_COLABORA_REFUGIO,

    //LOCAL

    ROLE_LOCAL_CREA,
    ROLE_LOCAL_TIPO,

    // VETERINARIA

    ROLE_VETERINARIA,
    ROLE_VETERINARIO,


    //ANIMALES

    ROLE_ANIMAL_RAZA,
    ROLE_ANIMAL_TAMANO,
    ROLE_ANIMAL_TIPO,

    //POSTULANTES-COLABORADOR
    ROLE_POSTULANTE_COLABORADOR




}
